/**
 * Self-contained HTML report generator.
 *
 * Design constraints that shaped this file:
 *
 *   ONE FILE, NO NETWORK. Screenshots are inlined as data URIs, CSS and JS are
 *   embedded. The output can be emailed, attached to a ticket, or opened from a
 *   USB stick five years from now and still render identically. Anything loaded
 *   from a CDN would eventually 404 and take the report's styling with it.
 *
 *   PRINTS TO PDF PROPERLY. The "professional enough to send to a CTO" bar in
 *   practice means "Ctrl+P produces something presentable", so there is a real
 *   print stylesheet rather than an afterthought.
 *
 *   HONEST BY CONSTRUCTION. Every finding renders its measured facts with their
 *   source, and AI-written prose is visually marked as such. A reader must be
 *   able to tell at a glance which claims are measurements and which are
 *   interpretation.
 */

import {
  CATEGORY_LABELS,
  scoreBand,
  type Category,
  type Finding,
  type Severity,
} from '@webqa/shared';
import type { AuditResult } from '../pipeline.js';
import type { EvidenceStore } from '../store/evidence.js';

const SEVERITY_ORDER: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];

/** Escape text for insertion into HTML. Everything user- or site-derived goes through this. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function formatMs(ms: number | null): string {
  if (ms === null || ms === undefined) return '—';
  if (ms < 1000) return `${Math.round(ms)} ms`;
  return `${(ms / 1000).toFixed(2)} s`;
}

function formatDuration(ms: number): string {
  const seconds = Math.round(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  return `${minutes}m ${seconds % 60}s`;
}

export interface RenderOptions {
  result: AuditResult;
  evidence: EvidenceStore;
  /** Inline screenshots as data URIs. Off produces a much smaller file. */
  inlineScreenshots?: boolean;
  /** Cap on inlined screenshots, to keep the file a sane size. */
  maxInlineScreenshots?: number;
}

export async function renderHtmlReport(options: RenderOptions): Promise<string> {
  const { result, evidence } = options;
  const inline = options.inlineScreenshots ?? true;
  const maxInline = options.maxInlineScreenshots ?? 40;

  // Resolve screenshots to data URIs up front so the template stays synchronous.
  const screenshotData = new Map<string, string>();
  if (inline) {
    const keys = new Set<string>();
    for (const page of result.pages) {
      if (page.screenshotKey) keys.add(page.screenshotKey);
    }
    for (const finding of result.findings) {
      for (const occurrence of finding.occurrences) {
        for (const artifact of occurrence.artifacts) {
          if (artifact.kind === 'SCREENSHOT' && artifact.storageKey) keys.add(artifact.storageKey);
        }
      }
    }
    let count = 0;
    for (const key of keys) {
      if (count >= maxInline) break;
      const uri = await evidence.readAsDataUri(result.auditId, key);
      if (uri) {
        screenshotData.set(key, uri);
        count += 1;
      }
    }
  }

  const histogram = result.stats.findingsBySeverity;
  const totalFindings = result.findings.length;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(hostOf(result.url))} Site Audit</title>
<style>${STYLES}</style>
</head>
<body>
<div class="wrap">

  ${renderHeader(result)}
  ${renderScoreboard(result)}
  ${renderSummary(result)}
  ${renderSeverityStrip(histogram, totalFindings)}
  ${renderFindings(result, screenshotData)}
  ${renderPerformance(result)}
  ${renderPages(result, screenshotData)}
  ${renderMethodology(result)}

  <footer class="foot">
    <p>Generated by <strong>webQA</strong> — automated black-box website audit.</p>
    <p class="muted">Audit <code>${esc(result.auditId)}</code> · ${esc(new Date(result.finishedAt).toLocaleString())}</p>
  </footer>
</div>
<script>${SCRIPT}</script>
</body>
</html>`;
}

// ── Sections ───────────────────────────────────────────────────────────────

function renderHeader(result: AuditResult): string {
  const statusClass =
    result.status === 'COMPLETED' ? 'ok' : result.status === 'PARTIAL' ? 'warn' : 'bad';

  return `
  <header class="head">
    <div class="head-main">
      <div class="eyebrow">Website QA &amp; Optimization Audit</div>
      <h1>${esc(hostOf(result.url))}</h1>
      <a class="target" href="${esc(result.url)}" rel="noreferrer noopener" target="_blank">${esc(result.url)}</a>
    </div>
    <div class="head-meta">
      <span class="pill pill-${statusClass}">${esc(result.status)}</span>
      <dl>
        <div><dt>Completed</dt><dd>${esc(new Date(result.finishedAt).toLocaleString())}</dd></div>
        <div><dt>Duration</dt><dd>${esc(formatDuration(result.stats.durationMs))}</dd></div>
        <div><dt>Pages</dt><dd>${result.stats.pagesCrawled}</dd></div>
        <div><dt>Device</dt><dd>${esc(result.config.device)} · ${esc(result.config.network)}</dd></div>
      </dl>
    </div>
  </header>
  ${
    result.status === 'PARTIAL'
      ? `<div class="notice notice-warn"><strong>Partial audit.</strong> ${esc(result.error ?? 'The audit stopped before completing every stage — usually the time budget. Findings below are accurate for the pages that were probed.')}</div>`
      : ''
  }
  ${
    result.status === 'FAILED'
      ? `<div class="notice notice-bad"><strong>Audit failed.</strong> ${esc(result.error ?? 'Unknown error')}</div>`
      : ''
  }`;
}

function renderScoreboard(result: AuditResult): string {
  const { overall, categories } = result.scores;
  const band = scoreBand(overall);

  const dial = (score: number): string => {
    const circumference = 2 * Math.PI * 52;
    const offset = circumference * (1 - score / 100);
    return `
      <svg viewBox="0 0 120 120" class="dial" role="img" aria-label="Overall score ${score} out of 100">
        <circle cx="60" cy="60" r="52" class="dial-track"></circle>
        <circle cx="60" cy="60" r="52" class="dial-value band-${scoreBand(score)}"
                stroke-dasharray="${circumference.toFixed(1)}"
                stroke-dashoffset="${offset.toFixed(1)}"></circle>
      </svg>`;
  };

  const categoryRows = (Object.keys(categories) as Category[])
    .map((category) => {
      const score = categories[category];
      return `
        <div class="cat">
          <div class="cat-top">
            <span class="cat-name">${esc(CATEGORY_LABELS[category])}</span>
            <span class="cat-score band-text-${scoreBand(score)}">${score}</span>
          </div>
          <div class="bar"><span class="bar-fill band-${scoreBand(score)}" style="width:${score}%"></span></div>
        </div>`;
    })
    .join('');

  return `
  <section class="scoreboard">
    <div class="overall">
      <div class="dial-wrap">
        ${dial(overall)}
        <div class="dial-label">
          <span class="dial-number band-text-${band}">${overall}</span>
          <span class="dial-of">/ 100</span>
        </div>
      </div>
      <div class="overall-text">
        <h2>Website Health Score</h2>
        <p class="muted">Weighted across eight categories. Higher is better.</p>
      </div>
    </div>
    <div class="cats">${categoryRows}</div>
  </section>`;
}

function renderSummary(result: AuditResult): string {
  const { summary } = result;

  const list = (items: string[], className: string): string =>
    items.length === 0
      ? ''
      : `<ul class="${className}">${items.map((item) => `<li>${esc(item)}</li>`).join('')}</ul>`;

  return `
  <section class="card summary">
    <div class="card-head">
      <h2>Executive Summary</h2>
      <span class="tag ${summary.generatedBy === 'AI' ? 'tag-ai' : 'tag-auto'}">
        ${summary.generatedBy === 'AI' ? 'AI-written' : 'Generated from metrics'}
      </span>
    </div>
    <p class="lede">${esc(summary.text)}</p>
    <div class="summary-cols">
      ${
        summary.topRisks.length > 0
          ? `<div><h3>Needs attention now</h3>${list(summary.topRisks, 'risks')}</div>`
          : ''
      }
      ${
        summary.quickWins.length > 0
          ? `<div><h3>Quick wins</h3>${list(summary.quickWins, 'wins')}</div>`
          : ''
      }
    </div>
  </section>`;
}

function renderSeverityStrip(histogram: Record<string, number>, total: number): string {
  const stats = [
    { label: 'Findings', value: total, className: '' },
    { label: 'Critical', value: histogram.CRITICAL ?? 0, className: 'sev-critical' },
    { label: 'High', value: histogram.HIGH ?? 0, className: 'sev-high' },
    { label: 'Medium', value: histogram.MEDIUM ?? 0, className: 'sev-medium' },
    { label: 'Low', value: histogram.LOW ?? 0, className: 'sev-low' },
    { label: 'Info', value: histogram.INFO ?? 0, className: 'sev-info' },
  ];

  return `
  <section class="strip">
    ${stats
      .map(
        (stat) => `
      <div class="strip-item ${stat.className}">
        <span class="strip-value">${stat.value}</span>
        <span class="strip-label">${esc(stat.label)}</span>
      </div>`,
      )
      .join('')}
  </section>`;
}

function renderFindings(result: AuditResult, screenshots: Map<string, string>): string {
  if (result.findings.length === 0) {
    return `
    <section class="card">
      <h2>Findings</h2>
      <p class="empty">No issues were detected across ${result.stats.pagesCrawled} page(s). That is a genuinely good result — but note that an automated audit checks what it can measure, not everything that could be wrong.</p>
    </section>`;
  }

  const categories = [...new Set(result.findings.map((finding) => finding.category))];

  const filters = `
    <div class="filters no-print">
      <div class="filter-group">
        <span class="filter-label">Severity</span>
        ${SEVERITY_ORDER.map(
          (severity) =>
            `<button class="chip chip-${severity.toLowerCase()}" data-filter="severity" data-value="${severity}" aria-pressed="false">${severity}</button>`,
        ).join('')}
      </div>
      <div class="filter-group">
        <span class="filter-label">Category</span>
        ${categories
          .map(
            (category) =>
              `<button class="chip" data-filter="category" data-value="${category}" aria-pressed="false">${esc(CATEGORY_LABELS[category])}</button>`,
          )
          .join('')}
      </div>
      <div class="filter-group">
        <span class="filter-label">Confidence</span>
        ${['CONFIRMED', 'LIKELY', 'POSSIBLE']
          .map(
            (confidence) =>
              `<button class="chip" data-filter="confidence" data-value="${confidence}" aria-pressed="false">${confidence}</button>`,
          )
          .join('')}
      </div>
      <button class="chip chip-clear" id="clearFilters">Clear all</button>
    </div>`;

  const grouped = SEVERITY_ORDER.map((severity) => ({
    severity,
    findings: result.findings.filter((finding) => finding.severity === severity),
  })).filter((group) => group.findings.length > 0);

  const body = grouped
    .map(
      (group) => `
      <div class="sev-group" data-severity-group="${group.severity}">
        <h3 class="sev-heading sev-${group.severity.toLowerCase()}">
          ${group.severity}
          <span class="count">${group.findings.length}</span>
        </h3>
        ${group.findings.map((finding) => renderFinding(finding, screenshots)).join('')}
      </div>`,
    )
    .join('');

  return `
  <section class="card findings-section">
    <div class="card-head">
      <h2>Findings</h2>
      <span class="muted" id="findingCount">${result.findings.length} shown</span>
    </div>
    <p class="muted section-note">
      Ordered by priority — a composite of severity, confidence, how much of the site is affected, and how much work the fix is.
      Every finding lists the measurements it was derived from.
    </p>
    ${filters}
    <div id="findingList">${body}</div>
    <p class="empty hidden" id="noMatches">No findings match the current filters.</p>
  </section>`;
}

function renderFinding(finding: Finding, screenshots: Map<string, string>): string {
  const confidencePercent = Math.round(finding.confidenceScore * 100);

  const facts = finding.measuredFacts
    .map(
      (fact) => `
      <tr>
        <th scope="row">${esc(fact.label)}</th>
        <td class="fact-value">${esc(fact.value)}${fact.unit ? ` ${esc(fact.unit)}` : ''}</td>
        <td class="fact-source">${esc(fact.source)}</td>
      </tr>`,
    )
    .join('');

  const pages = [...new Set(finding.occurrences.map((occurrence) => occurrence.pageUrl))];

  const occurrenceRows = finding.occurrences
    .slice(0, 25)
    .map(
      (occurrence) => `
      <li>
        <a href="${esc(occurrence.pageUrl)}" target="_blank" rel="noreferrer noopener">${esc(pathOf(occurrence.pageUrl))}</a>
        ${occurrence.selector ? `<code class="sel">${esc(occurrence.selector)}</code>` : ''}
        ${occurrence.detail ? `<span class="occ-detail">${esc(occurrence.detail)}</span>` : ''}
        ${occurrence.domSnippet ? `<pre class="snippet">${esc(occurrence.domSnippet)}</pre>` : ''}
      </li>`,
    )
    .join('');

  // First available screenshot across all occurrences.
  let shot: string | null = null;
  for (const occurrence of finding.occurrences) {
    for (const artifact of occurrence.artifacts) {
      if (artifact.kind === 'SCREENSHOT' && artifact.storageKey) {
        const uri = screenshots.get(artifact.storageKey);
        if (uri) { shot = uri; break; }
      }
    }
    if (shot) break;
  }

  const inlineEvidence = finding.occurrences
    .flatMap((occurrence) => occurrence.artifacts)
    .filter((artifact) => artifact.inline !== null && artifact.kind !== 'SCREENSHOT')
    .slice(0, 2);

  return `
  <article class="finding"
           data-severity="${finding.severity}"
           data-category="${finding.category}"
           data-confidence="${finding.confidence}">
    <header class="finding-head">
      <div class="finding-badges">
        <span class="badge badge-${finding.severity.toLowerCase()}">${finding.severity}</span>
        <span class="badge badge-cat">${esc(CATEGORY_LABELS[finding.category])}</span>
        <span class="badge badge-conf badge-conf-${finding.confidence.toLowerCase()}"
              title="How certain we are this is a real problem">
          ${finding.confidence} · ${confidencePercent}%
        </span>
        <span class="badge badge-effort">${finding.estimatedEffort} fix</span>
      </div>
      <h4>${esc(finding.title)}</h4>
      <div class="finding-reach">
        <span>${finding.affectedPageCount} page${finding.affectedPageCount === 1 ? '' : 's'}</span>
        <span>${finding.affectedElementCount} occurrence${finding.affectedElementCount === 1 ? '' : 's'}</span>
        ${finding.standardsRef ? `<span class="std">${esc(finding.standardsRef)}</span>` : ''}
        <span class="prio" title="Composite priority score">priority ${finding.priorityScore.toFixed(0)}</span>
      </div>
    </header>

    <p class="finding-desc">${esc(finding.description)}</p>

    ${
      facts
        ? `<details class="block" open>
        <summary><span class="block-title">How we know</span> <span class="block-hint">measured evidence</span></summary>
        <table class="facts"><tbody>${facts}</tbody></table>
      </details>`
        : ''
    }

    <details class="block">
      <summary><span class="block-title">Why this matters</span> <span class="block-hint">interpretation</span></summary>
      <p class="inference">${esc(finding.inference)}</p>
      <p class="impact-line"><strong>Impact:</strong> ${esc(finding.impact)}${finding.ai ? ' <span class="tag tag-ai tag-inline">AI</span>' : ''}</p>
      ${
        finding.ai
          ? `<div class="ai-block">
              <div class="ai-row"><strong>Likely root cause</strong><span>${esc(finding.ai.likelyRootCause)}</span></div>
              <div class="ai-row"><strong>Business impact</strong><span>${esc(finding.ai.businessImpact)}</span></div>
              ${
                finding.ai.caveats.length > 0
                  ? `<div class="ai-row"><strong>Caveats</strong><span>${finding.ai.caveats.map(esc).join(' · ')}</span></div>`
                  : ''
              }
              <p class="ai-note">Root-cause analysis written by ${esc(finding.ai.model)} from the evidence above.</p>
            </div>`
          : ''
      }
    </details>

    <details class="block block-fix" open>
      <summary><span class="block-title">Recommended fix</span> <span class="block-hint">${esc(finding.estimatedEffort.toLowerCase())} effort</span></summary>
      <p>${esc(finding.recommendation)}</p>
    </details>

    ${
      finding.reproduction
        ? `<details class="block">
            <summary><span class="block-title">How to reproduce</span></summary>
            <ol class="repro">${finding.reproduction.steps.map((step) => `<li>${esc(step)}</li>`).join('')}</ol>
            <p class="muted small">Environment: ${esc(finding.reproduction.environment)}</p>
          </details>`
        : ''
    }

    ${
      finding.technicalDetails
        ? `<details class="block">
            <summary><span class="block-title">Technical detail</span></summary>
            <pre class="tech">${esc(finding.technicalDetails)}</pre>
          </details>`
        : ''
    }

    ${
      shot
        ? `<details class="block">
            <summary><span class="block-title">Screenshot evidence</span></summary>
            <img class="shot" src="${shot}" alt="Screenshot captured while observing: ${esc(finding.title)}" loading="lazy">
          </details>`
        : ''
    }

    ${
      inlineEvidence.length > 0
        ? `<details class="block">
            <summary><span class="block-title">Raw evidence</span></summary>
            ${inlineEvidence
              .map(
                (artifact) =>
                  `<p class="muted small">${esc(artifact.caption)}</p><pre class="tech">${esc(JSON.stringify(artifact.inline, null, 2).slice(0, 3000))}</pre>`,
              )
              .join('')}
          </details>`
        : ''
    }

    <details class="block">
      <summary><span class="block-title">Where it occurs</span> <span class="block-hint">${pages.length} page${pages.length === 1 ? '' : 's'}</span></summary>
      <ul class="occurrences">${occurrenceRows}</ul>
      ${
        finding.occurrences.length > 25
          ? `<p class="muted small">Showing 25 of ${finding.occurrences.length} occurrences.</p>`
          : ''
      }
    </details>
  </article>`;
}

function renderPerformance(result: AuditResult): string {
  const pagesWithVitals = result.observations.filter((page) => page.vitals);
  if (pagesWithVitals.length === 0) return '';

  const median = (values: number[]): number | null => {
    const sorted = values.filter((value) => Number.isFinite(value)).sort((a, b) => a - b);
    if (sorted.length === 0) return null;
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
  };

  const pick = (selector: (page: (typeof pagesWithVitals)[number]) => number | null | undefined): number | null =>
    median(pagesWithVitals.map(selector).filter((value): value is number => typeof value === 'number'));

  const vitals = [
    { label: 'LCP', value: pick((p) => p.vitals?.lcpMs), format: formatMs, good: 2500, poor: 4000 },
    { label: 'FCP', value: pick((p) => p.vitals?.fcpMs), format: formatMs, good: 1800, poor: 3000 },
    { label: 'TTFB', value: pick((p) => p.vitals?.ttfbMs), format: formatMs, good: 800, poor: 1800 },
    { label: 'TBT', value: pick((p) => p.vitals?.tbtMs), format: formatMs, good: 200, poor: 600 },
    { label: 'CLS', value: pick((p) => p.vitals?.cls), format: (v: number | null) => (v === null ? '—' : v.toFixed(3)), good: 0.1, poor: 0.25 },
    { label: 'INP', value: pick((p) => p.vitals?.inpMs), format: formatMs, good: 200, poor: 500 },
  ];

  const payload = new Map<string, number>();
  let totalBytes = 0;
  let thirdPartyBytes = 0;
  let requestCount = 0;
  for (const page of result.observations) {
    for (const request of page.requests) {
      const bytes = request.transferSizeBytes ?? 0;
      totalBytes += bytes;
      requestCount += 1;
      if (request.isThirdParty) thirdPartyBytes += bytes;
      payload.set(request.resourceKind, (payload.get(request.resourceKind) ?? 0) + bytes);
    }
  }

  const payloadRows = [...payload.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(
      ([kind, bytes]) => `
      <div class="pay-row">
        <span class="pay-name">${esc(kind)}</span>
        <div class="bar"><span class="bar-fill bar-neutral" style="width:${totalBytes > 0 ? ((bytes / totalBytes) * 100).toFixed(1) : 0}%"></span></div>
        <span class="pay-bytes">${esc(formatBytes(bytes))}</span>
      </div>`,
    )
    .join('');

  const slowest = result.observations
    .filter((page) => typeof page.vitals?.lcpMs === 'number')
    .sort((a, b) => (b.vitals!.lcpMs ?? 0) - (a.vitals!.lcpMs ?? 0))
    .slice(0, 8);

  return `
  <section class="card">
    <h2>Performance Overview</h2>
    <p class="muted section-note">Medians across ${pagesWithVitals.length} probed page(s) — a median rather than a mean, so one pathological page does not define the picture.</p>

    <div class="vitals">
      ${vitals
        .map((vital) => {
          const band =
            vital.value === null ? 'none' : vital.value <= vital.good ? 'good' : vital.value <= vital.poor ? 'fair' : 'poor';
          return `
          <div class="vital band-border-${band}">
            <span class="vital-label">${esc(vital.label)}</span>
            <span class="vital-value band-text-${band}">${esc(vital.format(vital.value))}</span>
            <span class="vital-target">target ≤ ${esc(vital.label === 'CLS' ? vital.good.toString() : formatMs(vital.good))}</span>
          </div>`;
        })
        .join('')}
    </div>

    <div class="perf-grid">
      <div>
        <h3>Payload composition</h3>
        <div class="payload">${payloadRows}</div>
        <p class="muted small">
          ${esc(formatBytes(totalBytes))} across ${requestCount} requests ·
          third-party ${esc(formatBytes(thirdPartyBytes))} (${totalBytes > 0 ? ((thirdPartyBytes / totalBytes) * 100).toFixed(0) : 0}%)
        </p>
      </div>
      <div>
        <h3>Slowest pages by LCP</h3>
        <table class="mini">
          <thead><tr><th>Page</th><th>LCP</th></tr></thead>
          <tbody>
            ${slowest
              .map(
                (page) => `
              <tr>
                <td class="ellipsis"><a href="${esc(page.url)}" target="_blank" rel="noreferrer noopener">${esc(pathOf(page.url))}</a></td>
                <td class="num">${esc(formatMs(page.vitals?.lcpMs ?? null))}</td>
              </tr>`,
              )
              .join('')}
          </tbody>
        </table>
      </div>
    </div>
  </section>`;
}

function renderPages(result: AuditResult, screenshots: Map<string, string>): string {
  if (result.pages.length === 0) return '';

  const sorted = [...result.pages].sort((a, b) => a.healthScore - b.healthScore);

  return `
  <section class="card">
    <div class="card-head">
      <h2>Page Health</h2>
      <span class="muted">${result.pages.length} page${result.pages.length === 1 ? '' : 's'} probed</span>
    </div>
    <p class="muted section-note">Scored the same way as the site, using only the findings that occur on each page. Worst first.</p>
    <table class="pages">
      <thead>
        <tr>
          <th>Page</th><th class="num">Score</th><th class="num">Issues</th>
          <th class="num">Status</th><th class="num">Load</th><th class="num">Weight</th>
        </tr>
      </thead>
      <tbody>
        ${sorted
          .map((page) => {
            const band = scoreBand(page.healthScore);
            const shot = page.screenshotKey ? screenshots.get(page.screenshotKey) : null;
            const severityDots = SEVERITY_ORDER.filter((severity) => (page.severityCounts[severity] ?? 0) > 0)
              .map(
                (severity) =>
                  `<span class="dot dot-${severity.toLowerCase()}" title="${page.severityCounts[severity]} ${severity}">${page.severityCounts[severity]}</span>`,
              )
              .join('');

            return `
            <tr>
              <td class="page-cell">
                ${shot ? `<img class="thumb" src="${shot}" alt="" loading="lazy">` : '<span class="thumb thumb-empty"></span>'}
                <span class="page-info">
                  <a href="${esc(page.url)}" target="_blank" rel="noreferrer noopener">${esc(page.title || pathOf(page.url))}</a>
                  <small>${esc(pathOf(page.url))}</small>
                </span>
              </td>
              <td class="num"><span class="score-pill band-${band}">${page.healthScore}</span></td>
              <td class="num"><span class="dots">${severityDots || '<span class="muted">—</span>'}</span></td>
              <td class="num">${page.probeError ? '<span class="bad-text">error</span>' : (page.httpStatus ?? '—')}</td>
              <td class="num">${esc(formatMs(page.loadTimeMs))}</td>
              <td class="num">${esc(formatBytes(page.bytesTransferred))}</td>
            </tr>`;
          })
          .join('')}
      </tbody>
    </table>
  </section>`;
}

function renderMethodology(result: AuditResult): string {
  const aiCalls = result.aiCalls.filter((call) => !call.error).length;
  const aiTokens = result.aiCalls.reduce(
    (sum, call) => sum + (call.inputTokens ?? 0) + (call.outputTokens ?? 0),
    0,
  );

  return `
  <section class="card method">
    <h2>Method &amp; Scope</h2>
    <div class="method-grid">
      <div>
        <h3>What was tested</h3>
        <ul>
          <li>${result.stats.pagesCrawled} page(s) loaded in a real Chromium browser at ${esc(result.config.device.toLowerCase())} viewport</li>
          <li>${result.stats.requestsObserved} network request(s) observed, ${esc(formatBytes(result.stats.bytesTransferred))} transferred</li>
          <li>${result.stats.interactionsTested} interactive control(s) clicked and observed</li>
          <li>${result.stats.linksChecked} link target(s) verified · ${result.stats.brokenLinks} broken</li>
          <li>${result.stats.consoleErrors} console error(s) and uncaught exception(s) captured</li>
          <li>Accessibility scanned with axe-core against WCAG 2.1 A/AA and 2.2 AA</li>
        </ul>
      </div>
      <div>
        <h3>How to read this report</h3>
        <ul>
          <li><strong>Measured facts</strong> are observations from the browser. They are not estimates.</li>
          <li><strong>Interpretation</strong> is our reasoning from those facts, and is labelled separately.</li>
          <li><strong>Confidence</strong> — CONFIRMED means we observed the failure directly; POSSIBLE means the evidence is suggestive but a benign explanation exists.</li>
          <li><strong>Priority</strong> combines severity, confidence, how much of the site is affected, and effort.</li>
          ${aiCalls > 0 ? `<li>AI enrichment: ${aiCalls} successful call(s), ${aiTokens.toLocaleString()} tokens. The model annotated findings; it never created them.</li>` : '<li>AI enrichment was not used for this audit — all findings and prose are rule-generated.</li>'}
        </ul>
      </div>
      <div>
        <h3>Limits of this audit</h3>
        <ul>
          <li>Black-box only — no source code, backend, or database access.</li>
          <li>Security checks are <strong>passive</strong>: response headers and transport configuration observed during normal page loads. No active scanning or probing was performed.</li>
          <li>Interaction testing deliberately skips anything that looks destructive (delete, purchase, logout, submit), so those paths are untested.</li>
          <li>Pages behind authentication were not tested.</li>
          <li>A single measurement per page — network timing varies between runs.</li>
          ${result.site.skipped.length > 0 ? `<li>${result.site.skipped.length} URL(s) were deliberately skipped (crawl traps, external hosts, non-page assets).</li>` : ''}
        </ul>
      </div>
    </div>
    <details class="block">
      <summary><span class="block-title">Configuration used</span></summary>
      <pre class="tech">${esc(JSON.stringify(result.config, null, 2))}</pre>
    </details>
  </section>`;
}

// ── helpers ────────────────────────────────────────────────────────────────

function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}

function pathOf(url: string): string {
  try {
    const parsed = new URL(url);
    return (parsed.pathname + parsed.search) || '/';
  } catch {
    return url;
  }
}

// ── styles ─────────────────────────────────────────────────────────────────

const STYLES = `
:root{
  --bg:#f6f7f9; --surface:#ffffff; --surface-2:#f0f2f5; --border:#dfe3e8;
  --text:#12161c; --muted:#5c6674; --accent:#2f5fd8;
  --good:#0f7b4f; --fair:#b26a00; --poor:#c0392b;
  --critical:#a01b1b; --high:#c0392b; --medium:#b26a00; --low:#2f5fd8; --info:#5c6674;
  --radius:10px; --shadow:0 1px 2px rgba(16,24,40,.06),0 1px 3px rgba(16,24,40,.1);
  --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --bg:#0e1117; --surface:#161b22; --surface-2:#1c2230; --border:#2b3242;
    --text:#e6edf3; --muted:#9aa5b4; --accent:#6f9cff;
    --good:#3fb984; --fair:#e0a437; --poor:#f2685c;
    --critical:#ff6b6b; --high:#f2685c; --medium:#e0a437; --low:#6f9cff; --info:#9aa5b4;
    --shadow:0 1px 2px rgba(0,0,0,.4);
  }
}
:root[data-theme="dark"]{
  --bg:#0e1117; --surface:#161b22; --surface-2:#1c2230; --border:#2b3242;
  --text:#e6edf3; --muted:#9aa5b4; --accent:#6f9cff;
  --good:#3fb984; --fair:#e0a437; --poor:#f2685c;
  --critical:#ff6b6b; --high:#f2685c; --medium:#e0a437; --low:#6f9cff; --info:#9aa5b4;
}
*{box-sizing:border-box}
body{
  margin:0;background:var(--bg);color:var(--text);
  font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  -webkit-font-smoothing:antialiased;
}
.wrap{max-width:1080px;margin:0 auto;padding:32px 20px 64px}
h1,h2,h3,h4{line-height:1.25;margin:0}
a{color:var(--accent)}
code{font-family:var(--mono);font-size:.86em}
.muted{color:var(--muted)}
.small{font-size:.85em}
.hidden{display:none !important}
.num{text-align:right;font-variant-numeric:tabular-nums}
.ellipsis{max-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}

/* header */
.head{display:flex;flex-wrap:wrap;gap:24px;justify-content:space-between;align-items:flex-start;margin-bottom:24px}
/* Labels and measurements use the mono face throughout: this is a measurement
   document, and the typography should say so rather than dressing it up. */
.eyebrow{font-family:var(--mono);font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted);font-weight:600}
.head h1{font-size:30px;margin:4px 0 2px;letter-spacing:-.02em}
.target{font-size:13px;word-break:break-all}
.head-meta{text-align:right}
.head-meta dl{display:grid;grid-template-columns:auto auto;gap:2px 16px;margin:10px 0 0;font-size:12.5px;justify-content:end}
.head-meta dl>div{display:contents}
.head-meta dt{color:var(--muted)}
.head-meta dd{margin:0;text-align:right;font-weight:600}
.pill{display:inline-block;padding:3px 10px;border-radius:99px;font-size:11px;font-weight:700;letter-spacing:.04em}
.pill-ok{background:color-mix(in srgb,var(--good) 16%,transparent);color:var(--good)}
.pill-warn{background:color-mix(in srgb,var(--fair) 16%,transparent);color:var(--fair)}
.pill-bad{background:color-mix(in srgb,var(--poor) 16%,transparent);color:var(--poor)}

.notice{border-radius:var(--radius);padding:12px 16px;margin-bottom:20px;font-size:14px;border:1px solid}
.notice-warn{background:color-mix(in srgb,var(--fair) 10%,var(--surface));border-color:color-mix(in srgb,var(--fair) 35%,transparent)}
.notice-bad{background:color-mix(in srgb,var(--poor) 10%,var(--surface));border-color:color-mix(in srgb,var(--poor) 35%,transparent)}

/* cards */
.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:24px;margin-bottom:20px;box-shadow:var(--shadow)}
.card-head{display:flex;justify-content:space-between;align-items:baseline;gap:16px;margin-bottom:6px}
.card h2{font-size:19px;letter-spacing:-.01em}
.card h3{font-size:14px;margin:0 0 10px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}
.section-note{font-size:13px;margin:0 0 18px}
.empty{color:var(--muted);padding:16px 0}

/* scoreboard */
.scoreboard{display:grid;grid-template-columns:minmax(260px,1fr) 2fr;gap:28px;background:var(--surface);
  border:1px solid var(--border);border-radius:var(--radius);padding:28px;margin-bottom:20px;box-shadow:var(--shadow)}
.overall{display:flex;align-items:center;gap:20px}
.dial-wrap{position:relative;width:120px;height:120px;flex-shrink:0}
.dial{width:120px;height:120px;transform:rotate(-90deg)}
.dial-track{fill:none;stroke:var(--surface-2);stroke-width:10}
.dial-value{fill:none;stroke-width:10;stroke-linecap:round;transition:stroke-dashoffset .6s ease}
.dial-value.band-good{stroke:var(--good)} .dial-value.band-fair{stroke:var(--fair)} .dial-value.band-poor{stroke:var(--poor)}
.dial-label{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}
.dial-number{font-family:var(--mono);font-size:34px;font-weight:700;letter-spacing:-.04em;line-height:1}
.dial-of{font-size:11px;color:var(--muted)}
.overall-text h2{font-size:17px}
.cats{display:grid;grid-template-columns:1fr 1fr;gap:12px 24px;align-content:center}
.cat-top{display:flex;justify-content:space-between;font-size:13px;margin-bottom:4px}
.cat-name{color:var(--muted)}
.cat-score{font-family:var(--mono);font-weight:700;font-variant-numeric:tabular-nums}
.bar{height:6px;background:var(--surface-2);border-radius:99px;overflow:hidden}
.bar-fill{display:block;height:100%;border-radius:99px}
.bar-fill.band-good{background:var(--good)} .bar-fill.band-fair{background:var(--fair)} .bar-fill.band-poor{background:var(--poor)}
.bar-neutral{background:var(--accent);opacity:.7}
.band-text-good{color:var(--good)} .band-text-fair{color:var(--fair)} .band-text-poor{color:var(--poor)} .band-text-none{color:var(--muted)}
.band-border-good{border-left-color:var(--good) !important} .band-border-fair{border-left-color:var(--fair) !important}
.band-border-poor{border-left-color:var(--poor) !important} .band-border-none{border-left-color:var(--border) !important}

/* summary */
.summary .lede{font-size:16.5px;line-height:1.65;margin:8px 0 18px}
.summary-cols{display:grid;grid-template-columns:1fr 1fr;gap:24px}
.summary-cols ul{margin:0;padding-left:18px;font-size:14px}
.summary-cols li{margin-bottom:6px}
.risks li::marker{color:var(--poor)}
.wins li::marker{color:var(--good)}
.tag{font-size:10.5px;font-weight:700;letter-spacing:.05em;padding:3px 8px;border-radius:5px;text-transform:uppercase;white-space:nowrap}
.tag-ai{background:color-mix(in srgb,var(--accent) 16%,transparent);color:var(--accent)}
.tag-auto{background:var(--surface-2);color:var(--muted)}
.tag-inline{margin-left:4px;display:inline-block;vertical-align:1px}

/* severity strip */
.strip{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:20px}
.strip-item{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:14px;text-align:center;box-shadow:var(--shadow)}
.strip-value{display:block;font-family:var(--mono);font-size:25px;font-weight:700;line-height:1.1;font-variant-numeric:tabular-nums;letter-spacing:-.03em}
.strip-label{font-family:var(--mono);font-size:10.5px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}
.sev-critical .strip-value{color:var(--critical)} .sev-high .strip-value{color:var(--high)}
.sev-medium .strip-value{color:var(--medium)} .sev-low .strip-value{color:var(--low)} .sev-info .strip-value{color:var(--info)}

/* filters */
.filters{display:flex;flex-wrap:wrap;gap:16px;padding:14px;background:var(--surface-2);border-radius:8px;margin-bottom:20px}
.filter-group{display:flex;align-items:center;gap:6px;flex-wrap:wrap}
.filter-label{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);font-weight:600;margin-right:2px}
.chip{border:1px solid var(--border);background:var(--surface);color:var(--text);font:inherit;font-size:12px;
  padding:4px 10px;border-radius:99px;cursor:pointer;transition:all .12s}
.chip:hover{border-color:var(--accent)}
.chip[aria-pressed="true"]{background:var(--accent);color:#fff;border-color:var(--accent)}
.chip-clear{margin-left:auto;color:var(--muted)}

/* findings */
.sev-heading{font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin:26px 0 12px;display:flex;align-items:center;gap:8px}
.sev-heading .count{background:var(--surface-2);color:var(--muted);padding:1px 8px;border-radius:99px;font-size:11px}
.sev-heading.sev-critical{color:var(--critical)} .sev-heading.sev-high{color:var(--high)}
.sev-heading.sev-medium{color:var(--medium)} .sev-heading.sev-low{color:var(--low)} .sev-heading.sev-info{color:var(--info)}

.finding{border:1px solid var(--border);border-left:3px solid var(--border);border-radius:8px;padding:18px;margin-bottom:14px;background:var(--surface)}
.finding[data-severity="CRITICAL"]{border-left-color:var(--critical)}
.finding[data-severity="HIGH"]{border-left-color:var(--high)}
.finding[data-severity="MEDIUM"]{border-left-color:var(--medium)}
.finding[data-severity="LOW"]{border-left-color:var(--low)}
.finding[data-severity="INFO"]{border-left-color:var(--info)}
.finding-badges{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px}
.badge{font-size:10.5px;font-weight:700;letter-spacing:.04em;padding:3px 8px;border-radius:5px;background:var(--surface-2);color:var(--muted)}
.badge-critical{background:color-mix(in srgb,var(--critical) 16%,transparent);color:var(--critical)}
.badge-high{background:color-mix(in srgb,var(--high) 16%,transparent);color:var(--high)}
.badge-medium{background:color-mix(in srgb,var(--medium) 16%,transparent);color:var(--medium)}
.badge-low{background:color-mix(in srgb,var(--low) 16%,transparent);color:var(--low)}
.badge-info{background:var(--surface-2);color:var(--info)}
.badge-conf-confirmed{background:color-mix(in srgb,var(--good) 14%,transparent);color:var(--good)}
.badge-conf-possible{background:var(--surface-2);color:var(--muted)}
.finding h4{font-size:16.5px;margin:2px 0 6px;letter-spacing:-.01em}
.finding-reach{display:flex;flex-wrap:wrap;gap:12px;font-size:12px;color:var(--muted)}
.finding-reach .std{font-style:italic}
.finding-desc{margin:10px 0 14px;font-size:14.5px}

.block{border-top:1px solid var(--border);padding-top:10px;margin-top:10px}
.block>summary{cursor:pointer;list-style:none;display:flex;align-items:baseline;gap:8px;user-select:none}
.block>summary::-webkit-details-marker{display:none}
.block>summary::before{content:"▸";color:var(--muted);font-size:11px;transition:transform .15s}
.block[open]>summary::before{transform:rotate(90deg)}
.block-title{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}
.block-hint{font-size:11px;color:var(--muted)}
.block>*:not(summary){margin-top:10px}
.block-fix>summary .block-title{color:var(--good)}

.facts{width:100%;border-collapse:collapse;font-size:13px}
.facts th{text-align:left;font-weight:600;color:var(--muted);padding:4px 12px 4px 0;vertical-align:top;white-space:nowrap;width:1%}
.facts td{padding:4px 0;vertical-align:top}
.fact-value{font-family:var(--mono);font-size:12.5px;word-break:break-word}
.fact-source{color:var(--muted);font-size:11.5px;text-align:right;white-space:nowrap;padding-left:12px !important}
.inference{font-size:14px;line-height:1.65}
.impact-line{font-size:14px}
.ai-block{background:var(--surface-2);border-radius:8px;padding:12px 14px;font-size:13.5px}
.ai-row{display:grid;grid-template-columns:130px 1fr;gap:10px;margin-bottom:6px}
.ai-row strong{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em;padding-top:2px}
.ai-note{font-size:11.5px;color:var(--muted);margin:8px 0 0;font-style:italic}
.repro{font-size:14px;padding-left:20px;margin:8px 0}
.repro li{margin-bottom:4px}
.tech,.snippet{background:var(--surface-2);border-radius:6px;padding:10px 12px;font-family:var(--mono);font-size:12px;
  overflow-x:auto;white-space:pre-wrap;word-break:break-word;line-height:1.5;max-height:340px;overflow-y:auto}
.snippet{font-size:11.5px;margin:4px 0 0}
.shot{max-width:100%;border:1px solid var(--border);border-radius:6px;display:block}
.occurrences{list-style:none;padding:0;margin:0;font-size:13px}
.occurrences li{padding:6px 0;border-bottom:1px solid var(--border)}
.occurrences li:last-child{border-bottom:none}
.sel{background:var(--surface-2);padding:1px 5px;border-radius:4px;margin-left:6px;font-size:11.5px}
.occ-detail{color:var(--muted);margin-left:6px;font-size:12.5px}

/* performance */
.vitals{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin-bottom:24px}
.vital{background:var(--surface-2);border-left:3px solid var(--border);border-radius:6px;padding:12px 14px;display:flex;flex-direction:column;gap:2px}
.vital-label{font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:700}
.vital-value{font-family:var(--mono);font-size:21px;font-weight:700;font-variant-numeric:tabular-nums;letter-spacing:-.03em}
.vital-target{font-size:11px;color:var(--muted)}
.perf-grid{display:grid;grid-template-columns:1fr 1fr;gap:28px}
.pay-row{display:grid;grid-template-columns:80px 1fr 76px;align-items:center;gap:10px;margin-bottom:7px;font-size:12.5px}
.pay-name{color:var(--muted)}
.pay-bytes{text-align:right;font-variant-numeric:tabular-nums}
.mini{width:100%;border-collapse:collapse;font-size:13px;table-layout:fixed}
.mini th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);
  padding-bottom:6px;border-bottom:1px solid var(--border)}
.mini td{padding:5px 0;border-bottom:1px solid var(--border)}
.mini th:last-child,.mini td:last-child{text-align:right;width:80px}

/* page table */
.pages{width:100%;border-collapse:collapse;font-size:13px}
.pages th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);
  padding:0 8px 8px;border-bottom:1px solid var(--border)}
.pages td{padding:8px;border-bottom:1px solid var(--border);vertical-align:middle}
.page-cell{display:flex;align-items:center;gap:10px}
.thumb{width:52px;height:34px;object-fit:cover;object-position:top;border:1px solid var(--border);border-radius:4px;flex-shrink:0}
.thumb-empty{background:var(--surface-2);display:inline-block}
.page-info{display:flex;flex-direction:column;min-width:0}
.page-info a{font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:340px}
.page-info small{color:var(--muted);font-size:11.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:340px}
.score-pill{display:inline-block;min-width:34px;padding:2px 7px;border-radius:5px;font-weight:700;font-size:12px;color:#fff}
.score-pill.band-good{background:var(--good)} .score-pill.band-fair{background:var(--fair)} .score-pill.band-poor{background:var(--poor)}
.dots{display:inline-flex;gap:4px;justify-content:flex-end}
.dot{font-size:10.5px;font-weight:700;padding:1px 6px;border-radius:99px;color:#fff}
.dot-critical{background:var(--critical)} .dot-high{background:var(--high)} .dot-medium{background:var(--medium)}
.dot-low{background:var(--low)} .dot-info{background:var(--info)}
.bad-text{color:var(--poor);font-weight:600}

/* method */
.method-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:24px;margin-bottom:8px}
.method-grid ul{margin:0;padding-left:18px;font-size:13.5px}
.method-grid li{margin-bottom:6px}

.foot{text-align:center;color:var(--muted);font-size:12.5px;padding-top:24px;border-top:1px solid var(--border)}
.foot p{margin:2px 0}

@media (max-width:820px){
  .scoreboard,.perf-grid,.summary-cols{grid-template-columns:1fr}
  .cats{grid-template-columns:1fr}
  .strip{grid-template-columns:repeat(3,1fr)}
  .head-meta{text-align:left}
  .head-meta dl{justify-content:start}
  .ai-row{grid-template-columns:1fr}
}

@media print{
  :root{--bg:#fff;--surface:#fff;--surface-2:#f4f4f4;--border:#ccc;--text:#000;--muted:#555}
  body{font-size:10.5pt}
  .wrap{max-width:none;padding:0}
  .no-print{display:none !important}
  .card,.scoreboard,.strip-item{box-shadow:none;break-inside:avoid;page-break-inside:avoid}
  .finding{break-inside:avoid;page-break-inside:avoid}
  /* Everything expanded, so nothing is lost in a printed copy. */
  details{display:block}
  details>summary{list-style:none}
  details:not([open])>*:not(summary){display:block !important}
  .tech,.snippet{max-height:none;overflow:visible}
  .thumb,.shot{max-width:340px}
  a{color:#000;text-decoration:none}
  h2{page-break-after:avoid}
}
`;

// ── client script ──────────────────────────────────────────────────────────

const SCRIPT = `
(function(){
  "use strict";
  var active = { severity:new Set(), category:new Set(), confidence:new Set() };
  var findings = Array.prototype.slice.call(document.querySelectorAll('.finding'));
  var counter = document.getElementById('findingCount');
  var empty = document.getElementById('noMatches');

  function matches(el){
    for (var key in active){
      var set = active[key];
      if (set.size === 0) continue;
      if (!set.has(el.dataset[key])) return false;
    }
    return true;
  }

  function apply(){
    var shown = 0;
    findings.forEach(function(el){
      var ok = matches(el);
      el.classList.toggle('hidden', !ok);
      if (ok) shown++;
    });

    // Hide a severity heading when every finding beneath it is filtered out.
    document.querySelectorAll('.sev-group').forEach(function(group){
      var visible = group.querySelectorAll('.finding:not(.hidden)').length;
      group.classList.toggle('hidden', visible === 0);
    });

    if (counter) counter.textContent = shown + ' of ' + findings.length + ' shown';
    if (empty) empty.classList.toggle('hidden', shown !== 0);
  }

  document.querySelectorAll('.chip[data-filter]').forEach(function(chip){
    chip.addEventListener('click', function(){
      var set = active[chip.dataset.filter];
      if (!set) return;
      var pressed = chip.getAttribute('aria-pressed') === 'true';
      if (pressed) set.delete(chip.dataset.value); else set.add(chip.dataset.value);
      chip.setAttribute('aria-pressed', String(!pressed));
      apply();
    });
  });

  var clear = document.getElementById('clearFilters');
  if (clear) clear.addEventListener('click', function(){
    Object.keys(active).forEach(function(k){ active[k].clear(); });
    document.querySelectorAll('.chip[data-filter]').forEach(function(c){ c.setAttribute('aria-pressed','false'); });
    apply();
  });
})();
`;
